<?php

/**
* @file
* Install file for the ausy_annual.
*/

/**
 * Install hook.
 *
 * @throws \Exception
 *   If something goes wrong.
 */
function ausy_annual_install() {
  $vid = 'ausy_annual_departments';
  $departments = ['Finance', 'IT', 'Consulting', 'Teaching'];

  foreach ($departments as $department) {
    \Drupal::entityTypeManager()->getStorage('taxonomy_term')->create([
      'name' => $department,
      'vid' => $vid,
    ])->save();
  }
}
